//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBLog
    {
        public int ID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string ControllerName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ActionName { get; set; }
        public string EXMsg { get; set; }
        public string UserMsg { get; set; }
    }
}
