//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceService
    {
        public int ID { get; set; }
        public int SerialNo { get; set; }
        public int InvoiceID { get; set; }
        public string ServiceName { get; set; }
        public decimal ServicePrice { get; set; }
        public decimal ServiceDiscount { get; set; }
        public decimal ServiceTotal { get; set; }
        public decimal ServiceNet { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual InvoiceMaster InvoiceMaster { get; set; }
        public virtual StoresBalance StoresBalance { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
