//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public int ID { get; set; }
        public int SerialNo { get; set; }
        public int InvoiceID { get; set; }
        public int ItemID { get; set; }
        public decimal Qty { get; set; }
        public decimal ItemDiscount { get; set; }
        public decimal Price { get; set; }
        public decimal ItemTotal { get; set; }
        public decimal ItemNet { get; set; }
    
        public virtual InvoiceMaster InvoiceMaster { get; set; }
        public virtual Item Item { get; set; }
    }
}
